config/routes.rb
Freak::Application.routes.draw do

  root :to => 'pages#home'
  
  get "pages/home"
  get "pages/restaurants"
  get "pages/activities"

  post '/login' => 'pages#login'
  post '/restaurants' => 'pages#create_restaurant'
  post '/activities' => 'pages#create_activity'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  belongs_to :restaurant
  
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  belongs_to :restaurant
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  
  has_many :restaurants
  has_many :activities
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def login
    user = User.where('LOWER(name) = ?', params[:name].downcase).first
    if user
      redirect_to pages_home_path(:user_id => user.id)
    else
      redirect_to pages_home_path, :notice => "I don't know you!"
    end
  end
  
  def home
    @user_id = params[:user_id]
  end

  def restaurants
    @user_id = params[:user_id]
    if @user_id.present?
      @restaurants = User.find(@user_id).restaurants
    else
      redirect_to pages_home_url, :notice => "You must login first."
    end
  end

  def create_restaurant
    @user_id = params[:user_id]
    if @user_id.present?
      Restaurant.create user_id: params[:user_id], name: params[:name]
      redirect_to pages_restaurants_url(user_id: @user_id), notice: 'Restaurant added!'
    else
      redirect_to pages_home_path, :notice => "You must login first."
    end
    
  end
  
  def activities
    @user_id = params[:user_id]
    if @user_id.present?
      @activities = User.find(@user_id).activities
    else
      redirect_to pages_home_path, :notice => "You must login first."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freak</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <% if @user_id.blank? %>
    <h1>Welcome!</h1>
  <% else %>
    <h1>Hello <%= User.find(@user_id).name %>!</h1>
    <nav>
      <%= link_to 'Home', root_url(:user_id => @user_id) %> |
      <%= link_to 'Restaurants', pages_restaurants_url(:user_id => @user_id) %> |
      <%= link_to 'Activites', pages_activities_url(:user_id => @user_id) %> |
      <%= link_to 'Logout', root_url %>
    </nav>
  <% end %>
</header>

<%= yield %>

</body>
</html>

app/views/pages/activities.html.erb
<h1>Activities</h1>

<ul>
  <% @activities.each do |activity| %>
    <li><%= activity.name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<% if notice.present? %>
  <p class="notice"><%= notice %></p>
<% end %>

<% if @user_id.blank? %>
  <%= form_tag '/login' do %>
  
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    <%= submit_tag "Login!" %>
  
  <% end %>
<% end %>

app/views/pages/restaurants.html.erb
<h1>Restaurants</h1>

<%= form_tag '/restaurants' do %>

  <%= label_tag :name, "Add Restaurant:" %>
  <%= text_field_tag :name %>
  <%= hidden_field_tag :user_id, @user_id %>
  <%= submit_tag "Add" %>
  
<% end %>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
  <% end %>
</ul>